<?php

namespace ApiBundle\Repository;

/**
 * UserLikeShopRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserLikeShopRepository extends \Doctrine\ORM\EntityRepository
{
}
